/* 
 * h225_container0.h
 *
 * Header for saving the ID's for Ethereal protocol items
 *
 * H.323 for Ethereal
 *
 * Copyright (c) 2002 Koninklijke Philips NV
 *
 * The contents of this file are subject to the Mozilla Public License
 * Version 1.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS"
 * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
 * the License for the specific language governing rights and limitations
 * under the License.
 *
 * The Original Code is H.323 for Ethereal.
 *
 * The Initial Developer of the Original Code is Koninklijke Philips NV.
 *
 * All Rights Reserved.
 *
 * Contributor(s): ______________________________________.
 *
 *
 */
//
// h225_container0.h
//
// Code automatically generated by asnparse.
//

#ifndef H225_INTEGER_CONTAINER_0_H
#define  H225_INTEGER_CONTAINER_0_H

class H225_0_Integer_Container
{
  public:
    H225_0_Integer_Container();
    int ett_proto_H225; // Protocol itself
    int hf_proto_H225;  // Protocol itself
    int hf_h225_ReleaseCompleteReason_noBandwidth;
    int hf_h225_ReleaseCompleteReason_gatekeeperResources;
    int hf_h225_ReleaseCompleteReason_unreachableDestination;
    int hf_h225_ReleaseCompleteReason_destinationRejection;
    int hf_h225_ReleaseCompleteReason_invalidRevision;
    int hf_h225_ReleaseCompleteReason_noPermission;
    int hf_h225_ReleaseCompleteReason_unreachableGatekeeper;
    int hf_h225_ReleaseCompleteReason_gatewayResources;
    int hf_h225_ReleaseCompleteReason_badFormatAddress;
    int hf_h225_ReleaseCompleteReason_adaptiveBusy;
    int hf_h225_ReleaseCompleteReason_inConf;
    int hf_h225_ReleaseCompleteReason_undefinedReason;
    int hf_h225_ReleaseCompleteReason_facilityCallDeflection;
    int hf_h225_ReleaseCompleteReason_securityDenied;
    int hf_h225_ReleaseCompleteReason_calledPartyNotRegistered;
    int hf_h225_ReleaseCompleteReason_callerNotRegistered;
    int hf_h225_ReleaseCompleteReason_newConnectionNeeded;
    int hf_h225_ReleaseCompleteReason_replaceWithConferenceInvite;
    int ett_h225_ReleaseCompleteReason_choice;
    int hf_h225_ScnConnectionType_unknown;
    int hf_h225_ScnConnectionType_bChannel;
    int hf_h225_ScnConnectionType_hybrid2x64;
    int hf_h225_ScnConnectionType_hybrid384;
    int hf_h225_ScnConnectionType_hybrid1536;
    int hf_h225_ScnConnectionType_hybrid1920;
    int hf_h225_ScnConnectionType_multirate;
    int hf_h225_ScnConnectionAggregation_auto;
    int hf_h225_ScnConnectionAggregation_none;
    int hf_h225_ScnConnectionAggregation_h221;
    int hf_h225_ScnConnectionAggregation_bonded_mode1;
    int hf_h225_ScnConnectionAggregation_bonded_mode2;
    int hf_h225_ScnConnectionAggregation_bonded_mode3;
    int hf_h225_PresentationIndicator_presentationAllowed;
    int hf_h225_PresentationIndicator_presentationRestricted;
    int hf_h225_PresentationIndicator_addressNotAvailable;
    int hf_h225_FacilityReason_routeCallToGatekeeper;
    int hf_h225_FacilityReason_callForwarded;
    int hf_h225_FacilityReason_routeCallToMC;
    int hf_h225_FacilityReason_undefinedReason;
    int hf_h225_FacilityReason_conferenceListChoice;
    int hf_h225_FacilityReason_startH245;
    int hf_h225_FacilityReason_noH245;
    int hf_h225_TransportAddress_netBios;
    int hf_h225_TransportAddress_nsap;
    int ett_h225_TransportAddress_choice;
    int ett_h225_SupportedProtocols_choice;
    int hf_h225_H221NonStandard_t35CountryCode;
    int hf_h225_H221NonStandard_t35Extension;
    int hf_h225_H221NonStandard_manufacturerCode;
    int hf_h225_NonStandardIdentifier_object;
    int ett_h225_NonStandardIdentifier_choice;
    int hf_h225_AliasAddress_e164;
    int hf_h225_AliasAddress_h323_ID;
    int hf_h225_AliasAddress_url_ID;
    int hf_h225_AliasAddress_email_ID;
    int ett_h225_AliasAddress_choice;
    int hf_h225_PartyNumber_dataPartyNumber;
    int hf_h225_PartyNumber_telexPartyNumber;
    int hf_h225_PartyNumber_nationalStandardPartyNumber;
    int ett_h225_PartyNumber_choice;
    int hf_h225_PublicTypeOfNumber_unknown;
    int hf_h225_PublicTypeOfNumber_internationalNumber;
    int hf_h225_PublicTypeOfNumber_nationalNumber;
    int hf_h225_PublicTypeOfNumber_networkSpecificNumber;
    int hf_h225_PublicTypeOfNumber_subscriberNumber;
    int hf_h225_PublicTypeOfNumber_abbreviatedNumber;
    int hf_h225_PrivateTypeOfNumber_unknown;
    int hf_h225_PrivateTypeOfNumber_level2RegionalNumber;
    int hf_h225_PrivateTypeOfNumber_level1RegionalNumber;
    int hf_h225_PrivateTypeOfNumber_pISNSpecificNumber;
    int hf_h225_PrivateTypeOfNumber_localNumber;
    int hf_h225_PrivateTypeOfNumber_abbreviatedNumber;
    int hf_h225_UseSpecifiedTransport_tcp;
    int hf_h225_UseSpecifiedTransport_annexE;
    int hf_h225_SecurityServiceMode_none;
    int hf_h225_SecurityServiceMode_default;
    int ett_h225_SecurityServiceMode_choice;
    int hf_h225_H245Security_noSecurity;
    int ett_h225_H245Security_choice;
    int hf_h225_Q954Details_conferenceCalling;
    int hf_h225_Q954Details_threePartyService;
    int hf_h225_CallIdentifier_guid;
    int hf_h225_EncryptIntAlg_isoAlgorithm;
    int ett_h225_EncryptIntAlg_choice;
    int hf_h225_NonIsoIntegrityMechanism_hMAC_MD5;
    int hf_h225_NonIsoIntegrityMechanism_hMAC_iso10118_3;
    int ett_h225_NonIsoIntegrityMechanism_choice;
    int hf_h225_IntegrityMechanism_digSig;
    int hf_h225_IntegrityMechanism_iso9797;
    int ett_h225_IntegrityMechanism_choice;
    int hf_h225_ICV_algorithmOID;
    int hf_h225_ICV_icv;
    int ett_h225_CryptoH323Token_choice;
    int ett_h225_RasMessage_choice;
    int hf_h225_GatekeeperRejectReason_resourceUnavailable;
    int hf_h225_GatekeeperRejectReason_terminalExcluded;
    int hf_h225_GatekeeperRejectReason_invalidRevision;
    int hf_h225_GatekeeperRejectReason_undefinedReason;
    int hf_h225_GatekeeperRejectReason_securityDenial;
    int hf_h225_RegistrationRejectReason_discoveryRequired;
    int hf_h225_RegistrationRejectReason_invalidRevision;
    int hf_h225_RegistrationRejectReason_invalidCallSignalAddress;
    int hf_h225_RegistrationRejectReason_invalidRASAddress;
    int hf_h225_RegistrationRejectReason_invalidTerminalType;
    int hf_h225_RegistrationRejectReason_undefinedReason;
    int hf_h225_RegistrationRejectReason_transportNotSupported;
    int hf_h225_RegistrationRejectReason_transportQOSNotSupported;
    int hf_h225_RegistrationRejectReason_resourceUnavailable;
    int hf_h225_RegistrationRejectReason_invalidAlias;
    int hf_h225_RegistrationRejectReason_securityDenial;
    int hf_h225_RegistrationRejectReason_fullRegistrationRequired;
    int ett_h225_RegistrationRejectReason_choice;
    int hf_h225_UnregRequestReason_reregistrationRequired;
    int hf_h225_UnregRequestReason_ttlExpired;
    int hf_h225_UnregRequestReason_securityDenial;
    int hf_h225_UnregRequestReason_undefinedReason;
    int hf_h225_UnregRejectReason_notCurrentlyRegistered;
    int hf_h225_UnregRejectReason_callInProgress;
    int hf_h225_UnregRejectReason_undefinedReason;
    int hf_h225_UnregRejectReason_permissionDenied;
    int hf_h225_UnregRejectReason_securityDenial;
    int hf_h225_CallType_pointToPoint;
    int hf_h225_CallType_oneToN;
    int hf_h225_CallType_nToOne;
    int hf_h225_CallType_nToN;
    int hf_h225_CallModel_direct;
    int hf_h225_CallModel_gatekeeperRouted;
    int hf_h225_TransportQOS_endpointControlled;
    int hf_h225_TransportQOS_gatekeeperControlled;
    int hf_h225_TransportQOS_noControl;
    int hf_h225_UUIEsRequested_setup;
    int hf_h225_UUIEsRequested_callProceeding;
    int hf_h225_UUIEsRequested_connect;
    int hf_h225_UUIEsRequested_alerting;
    int hf_h225_UUIEsRequested_information;
    int hf_h225_UUIEsRequested_releaseComplete;
    int hf_h225_UUIEsRequested_facility;
    int hf_h225_UUIEsRequested_progress;
    int hf_h225_UUIEsRequested_empty;
    int hf_h225_AdmissionRejectReason_calledPartyNotRegistered;
    int hf_h225_AdmissionRejectReason_invalidPermission;
    int hf_h225_AdmissionRejectReason_requestDenied;
    int hf_h225_AdmissionRejectReason_undefinedReason;
    int hf_h225_AdmissionRejectReason_callerNotRegistered;
    int hf_h225_AdmissionRejectReason_routeCallToGatekeeper;
    int hf_h225_AdmissionRejectReason_invalidEndpointIdentifier;
    int hf_h225_AdmissionRejectReason_resourceUnavailable;
    int hf_h225_AdmissionRejectReason_securityDenial;
    int hf_h225_AdmissionRejectReason_qosControlNotSupported;
    int hf_h225_AdmissionRejectReason_incompleteAddress;
    int hf_h225_AdmissionRejectReason_aliasesInconsistent;
    int ett_h225_AdmissionRejectReason_choice;
    int hf_h225_BandRejectReason_notBound;
    int hf_h225_BandRejectReason_invalidConferenceID;
    int hf_h225_BandRejectReason_invalidPermission;
    int hf_h225_BandRejectReason_insufficientResources;
    int hf_h225_BandRejectReason_invalidRevision;
    int hf_h225_BandRejectReason_undefinedReason;
    int hf_h225_BandRejectReason_securityDenial;
    int hf_h225_LocationRejectReason_notRegistered;
    int hf_h225_LocationRejectReason_invalidPermission;
    int hf_h225_LocationRejectReason_requestDenied;
    int hf_h225_LocationRejectReason_undefinedReason;
    int hf_h225_LocationRejectReason_securityDenial;
    int hf_h225_LocationRejectReason_aliasesInconsistent;
    int ett_h225_LocationRejectReason_choice;
    int hf_h225_DisengageReason_forcedDrop;
    int hf_h225_DisengageReason_normalDrop;
    int hf_h225_DisengageReason_undefinedReason;
    int hf_h225_DisengageRejectReason_notRegistered;
    int hf_h225_DisengageRejectReason_requestToDropOther;
    int hf_h225_DisengageRejectReason_securityDenial;
    int ett_h225_TransportChannelInfo_sendAddress;
    int ett_h225_TransportChannelInfo_recvAddress;
    int hf_h225_InfoRequestNakReason_notRegistered;
    int hf_h225_InfoRequestNakReason_securityDenial;
    int hf_h225_InfoRequestNakReason_undefinedReason;
    int hf_h225_H323_UserInformation_user_data_protocol_discriminator;
    int hf_h225_H323_UserInformation_user_data_user_information;
    int hf_h225_H323_UU_PDU_h323_message_body_empty;
    int ett_h225_H323_UU_PDU_h323_message_body_choice;
    int hf_h225_ArrayOf_PASN_OctetString_array;
    int ett_h225_ArrayOf_NonStandardParameter;
    int ett_h225_ArrayOf_ClearToken;
    int ett_h225_ArrayOf_CryptoH323Token;
    int ett_h225_ArrayOf_AliasAddress;
    int hf_h225_Connect_UUIE_language_array;
    int hf_h225_ArrayOf_CallReferenceValue_array;
    int hf_h225_Setup_UUIE_conferenceGoal_create;
    int hf_h225_Setup_UUIE_conferenceGoal_join;
    int hf_h225_Setup_UUIE_conferenceGoal_invite;
    int hf_h225_Setup_UUIE_conferenceGoal_capability_negotiation;
    int hf_h225_Setup_UUIE_conferenceGoal_callIndependentSupplementaryService;
    int ett_h225_ArrayOf_H245Security;
    int ett_h225_Setup_UUIE_connectionParameters_connectionType;
    int hf_h225_Setup_UUIE_connectionParameters_numberOfScnConnections;
    int ett_h225_Setup_UUIE_connectionParameters_connectionAggregation;
    int hf_h225_Setup_UUIE_language_array;
    int ett_h225_ArrayOf_ConferenceList;
    int hf_h225_TransportAddress_ipAddress_ip;
    int hf_h225_TransportAddress_ipAddress_port;
    int hf_h225_TransportAddress_ipxAddress_node;
    int hf_h225_TransportAddress_ipxAddress_netnum;
    int hf_h225_TransportAddress_ipxAddress_port;
    int hf_h225_TransportAddress_ip6Address_ip;
    int hf_h225_TransportAddress_ip6Address_port;
    int ett_h225_ArrayOf_SupportedProtocols;
    int ett_h225_ArrayOf_DataRate;
    int ett_h225_ArrayOf_SupportedPrefix;
    int ett_h225_ArrayOf_TransportAddress;
    int ett_h225_ArrayOf_AlternateGK;
    int ett_h225_CryptoH323Token_cryptoEPPwdHash_alias;
    int ett_h225_CryptoH323Token_cryptoEPPwdHash_timeStamp;
    int ett_h225_CryptoH323Token_cryptoEPPwdHash_token;
    int hf_h225_CryptoH323Token_cryptoGKPwdHash_gatekeeperId;
    int ett_h225_CryptoH323Token_cryptoGKPwdHash_timeStamp;
    int ett_h225_CryptoH323Token_cryptoGKPwdHash_token;
    int ett_h225_ArrayOf_Endpoint;
    int ett_h225_ArrayOf_AuthenticationMechanism;
    int hf_h225_ArrayOf_PASN_ObjectId_array;
    int ett_h225_ArrayOf_IntegrityMechanism;
    int hf_h225_AdmissionConfirm_language_array;
    int ett_h225_ArrayOf_PartyNumber;
    int ett_h225_InfoRequestResponse_perCallInfo;
    int hf_h225_RTPSession_associatedSessionIds_array;
    int hf_h225_TransportAddress_ipSourceRoute_route_array;
    int hf_h225_TransportAddress_ipSourceRoute_routing_strict;
    int hf_h225_TransportAddress_ipSourceRoute_routing_loose;
    int ett_h225_ArrayOf_RTPSession;
    int ett_h225_ArrayOf_TransportChannelInfo;
    int hf_h225_ArrayOf_ConferenceIdentifier_array;
    int ett_h225_InfoRequestResponse_perCallInfo_subtype_pdu;
    int hf_h225_Information_UUIE_protocolIdentifier;
    int ett_h225_Information_UUIE_callIdentifier;
    int ett_h225_Information_UUIE_tokens;
    int ett_h225_Information_UUIE_cryptoTokens;
    int ett_h225_Information_UUIE_fastStart;
    int hf_h225_Information_UUIE_fastConnectRefused;
    int hf_h225_ReleaseComplete_UUIE_protocolIdentifier;
    int ett_h225_ReleaseComplete_UUIE_reason;
    int ett_h225_ReleaseComplete_UUIE_callIdentifier;
    int ett_h225_ReleaseComplete_UUIE_tokens;
    int ett_h225_ReleaseComplete_UUIE_cryptoTokens;
    int ett_h225_ReleaseComplete_UUIE_busyAddress;
    int ett_h225_ReleaseComplete_UUIE_presentationIndicator;
    int hf_h225_ReleaseComplete_UUIE_screeningIndicator;
    int hf_h225_Facility_UUIE_protocolIdentifier;
    int ett_h225_Facility_UUIE_alternativeAddress;
    int ett_h225_Facility_UUIE_alternativeAliasAddress;
    int hf_h225_Facility_UUIE_conferenceID;
    int ett_h225_Facility_UUIE_reason;
    int ett_h225_Facility_UUIE_callIdentifier;
    int ett_h225_Facility_UUIE_destExtraCallInfo;
    int ett_h225_Facility_UUIE_remoteExtensionAddress;
    int ett_h225_Facility_UUIE_tokens;
    int ett_h225_Facility_UUIE_cryptoTokens;
    int ett_h225_Facility_UUIE_conferences;
    int ett_h225_Facility_UUIE_h245Address;
    int ett_h225_Facility_UUIE_fastStart;
    int hf_h225_Facility_UUIE_multipleCalls;
    int hf_h225_Facility_UUIE_maintainConnection;
    int hf_h225_Facility_UUIE_fastConnectRefused;
    int hf_h225_CallLinkage_globalCallId;
    int hf_h225_CallLinkage_threadId;
    int ett_h225_VendorIdentifier_vendor;
    int hf_h225_VendorIdentifier_productId;
    int hf_h225_VendorIdentifier_versionId;
    int ett_h225_NonStandardParameter_nonStandardIdentifier;
    int hf_h225_NonStandardParameter_data;
    int ett_h225_PublicPartyNumber_publicTypeOfNumber;
    int hf_h225_PublicPartyNumber_publicNumberDigits;
    int ett_h225_PrivatePartyNumber_privateTypeOfNumber;
    int hf_h225_PrivatePartyNumber_privateNumberDigits;
    int ett_h225_AlternateTransportAddresses_annexE;
    int ett_h225_AlternateGK_rasAddress;
    int hf_h225_AlternateGK_gatekeeperIdentifier;
    int hf_h225_AlternateGK_needToRegister;
    int hf_h225_AlternateGK_priority;
    int ett_h225_AltGKInfo_alternateGatekeeper;
    int hf_h225_AltGKInfo_altGKisPermanent;
    int ett_h225_SecurityCapabilities_nonStandard;
    int ett_h225_SecurityCapabilities_encryption;
    int ett_h225_SecurityCapabilities_authenticaton;
    int ett_h225_SecurityCapabilities_integrity;
    int hf_h225_QseriesOptions_q932Full;
    int hf_h225_QseriesOptions_q951Full;
    int hf_h225_QseriesOptions_q952Full;
    int hf_h225_QseriesOptions_q953Full;
    int hf_h225_QseriesOptions_q955Full;
    int hf_h225_QseriesOptions_q956Full;
    int hf_h225_QseriesOptions_q957Full;
    int ett_h225_QseriesOptions_q954Info;
    int ett_h225_DataRate_nonStandardData;
    int hf_h225_DataRate_channelRate;
    int hf_h225_DataRate_channelMultiplier;
    int ett_h225_SupportedPrefix_nonStandardData;
    int ett_h225_SupportedPrefix_prefix;
    int hf_h225_GatekeeperConfirm_requestSeqNum;
    int hf_h225_GatekeeperConfirm_protocolIdentifier;
    int ett_h225_GatekeeperConfirm_nonStandardData;
    int hf_h225_GatekeeperConfirm_gatekeeperIdentifier;
    int ett_h225_GatekeeperConfirm_rasAddress;
    int ett_h225_GatekeeperConfirm_alternateGatekeeper;
    int ett_h225_GatekeeperConfirm_authenticationMode;
    int ett_h225_GatekeeperConfirm_tokens;
    int ett_h225_GatekeeperConfirm_cryptoTokens;
    int hf_h225_GatekeeperConfirm_algorithmOID;
    int ett_h225_GatekeeperConfirm_integrity;
    int ett_h225_GatekeeperConfirm_integrityCheckValue;
    int hf_h225_GatekeeperReject_requestSeqNum;
    int hf_h225_GatekeeperReject_protocolIdentifier;
    int ett_h225_GatekeeperReject_nonStandardData;
    int hf_h225_GatekeeperReject_gatekeeperIdentifier;
    int ett_h225_GatekeeperReject_rejectReason;
    int ett_h225_GatekeeperReject_altGKInfo;
    int ett_h225_GatekeeperReject_tokens;
    int ett_h225_GatekeeperReject_cryptoTokens;
    int ett_h225_GatekeeperReject_integrityCheckValue;
    int hf_h225_RegistrationReject_requestSeqNum;
    int hf_h225_RegistrationReject_protocolIdentifier;
    int ett_h225_RegistrationReject_nonStandardData;
    int ett_h225_RegistrationReject_rejectReason;
    int hf_h225_RegistrationReject_gatekeeperIdentifier;
    int ett_h225_RegistrationReject_altGKInfo;
    int ett_h225_RegistrationReject_tokens;
    int ett_h225_RegistrationReject_cryptoTokens;
    int ett_h225_RegistrationReject_integrityCheckValue;
    int hf_h225_UnregistrationRequest_requestSeqNum;
    int ett_h225_UnregistrationRequest_callSignalAddress;
    int ett_h225_UnregistrationRequest_endpointAlias;
    int ett_h225_UnregistrationRequest_nonStandardData;
    int hf_h225_UnregistrationRequest_endpointIdentifier;
    int ett_h225_UnregistrationRequest_alternateEndpoints;
    int hf_h225_UnregistrationRequest_gatekeeperIdentifier;
    int ett_h225_UnregistrationRequest_tokens;
    int ett_h225_UnregistrationRequest_cryptoTokens;
    int ett_h225_UnregistrationRequest_integrityCheckValue;
    int ett_h225_UnregistrationRequest_reason;
    int hf_h225_UnregistrationConfirm_requestSeqNum;
    int ett_h225_UnregistrationConfirm_nonStandardData;
    int ett_h225_UnregistrationConfirm_tokens;
    int ett_h225_UnregistrationConfirm_cryptoTokens;
    int ett_h225_UnregistrationConfirm_integrityCheckValue;
    int hf_h225_UnregistrationReject_requestSeqNum;
    int ett_h225_UnregistrationReject_rejectReason;
    int ett_h225_UnregistrationReject_nonStandardData;
    int ett_h225_UnregistrationReject_altGKInfo;
    int ett_h225_UnregistrationReject_tokens;
    int ett_h225_UnregistrationReject_cryptoTokens;
    int ett_h225_UnregistrationReject_integrityCheckValue;
    int hf_h225_AdmissionRequest_requestSeqNum;
    int ett_h225_AdmissionRequest_callType;
    int ett_h225_AdmissionRequest_callModel;
    int hf_h225_AdmissionRequest_endpointIdentifier;
    int ett_h225_AdmissionRequest_destinationInfo;
    int ett_h225_AdmissionRequest_destCallSignalAddress;
    int ett_h225_AdmissionRequest_destExtraCallInfo;
    int ett_h225_AdmissionRequest_srcInfo;
    int ett_h225_AdmissionRequest_srcCallSignalAddress;
    int hf_h225_AdmissionRequest_bandWidth;
    int hf_h225_AdmissionRequest_callReferenceValue;
    int ett_h225_AdmissionRequest_nonStandardData;
    int ett_h225_AdmissionRequest_callServices;
    int hf_h225_AdmissionRequest_conferenceID;
    int hf_h225_AdmissionRequest_activeMC;
    int hf_h225_AdmissionRequest_answerCall;
    int hf_h225_AdmissionRequest_canMapAlias;
    int ett_h225_AdmissionRequest_callIdentifier;
    int ett_h225_AdmissionRequest_srcAlternatives;
    int ett_h225_AdmissionRequest_destAlternatives;
    int hf_h225_AdmissionRequest_gatekeeperIdentifier;
    int ett_h225_AdmissionRequest_tokens;
    int ett_h225_AdmissionRequest_cryptoTokens;
    int ett_h225_AdmissionRequest_integrityCheckValue;
    int ett_h225_AdmissionRequest_transportQOS;
    int hf_h225_AdmissionRequest_willSupplyUUIEs;
    int ett_h225_AdmissionRequest_callLinkage;
    int hf_h225_AdmissionReject_requestSeqNum;
    int ett_h225_AdmissionReject_rejectReason;
    int ett_h225_AdmissionReject_nonStandardData;
    int ett_h225_AdmissionReject_altGKInfo;
    int ett_h225_AdmissionReject_tokens;
    int ett_h225_AdmissionReject_cryptoTokens;
    int ett_h225_AdmissionReject_callSignalAddress;
    int ett_h225_AdmissionReject_integrityCheckValue;
    int hf_h225_BandwidthRequest_requestSeqNum;
    int hf_h225_BandwidthRequest_endpointIdentifier;
    int hf_h225_BandwidthRequest_conferenceID;
    int hf_h225_BandwidthRequest_callReferenceValue;
    int ett_h225_BandwidthRequest_callType;
    int hf_h225_BandwidthRequest_bandWidth;
    int ett_h225_BandwidthRequest_nonStandardData;
    int ett_h225_BandwidthRequest_callIdentifier;
    int hf_h225_BandwidthRequest_gatekeeperIdentifier;
    int ett_h225_BandwidthRequest_tokens;
    int ett_h225_BandwidthRequest_cryptoTokens;
    int ett_h225_BandwidthRequest_integrityCheckValue;
    int hf_h225_BandwidthRequest_answeredCall;
    int ett_h225_BandwidthRequest_callLinkage;
    int hf_h225_BandwidthConfirm_requestSeqNum;
  private:
};

#endif // end of header file


// End of h225_container0.h
