/* 
 * h245_container3.cxx
 *
 * Source for saving the ID's for Ethereal protocol items
 *
 * H.323 for Ethereal
 *
 * Copyright (c) 2002 Koninklijke Philips NV
 *
 * The contents of this file are subject to the Mozilla Public License
 * Version 1.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS"
 * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
 * the License for the specific language governing rights and limitations
 * under the License.
 *
 * The Original Code is H.323 for Ethereal.
 *
 * The Initial Developer of the Original Code is Koninklijke Philips NV.
 *
 * All Rights Reserved.
 *
 * Contributor(s): ______________________________________.
 *
 *
 */

//
// h245_container3.cpp
//
// Code automatically generated by asnparse.
//

#include "h245_container3.h"

H245_3_Integer_Container::H245_3_Integer_Container()
{

  hf_h245_H263VideoCapability_qcifMPI = -1;
  hf_h245_H263VideoCapability_cifMPI = -1;
  hf_h245_H263VideoCapability_cif4MPI = -1;
  hf_h245_H263VideoCapability_cif16MPI = -1;
  hf_h245_H263VideoCapability_maxBitRate = -1;
  hf_h245_H263VideoCapability_unrestrictedVector = -1;
  hf_h245_H263VideoCapability_arithmeticCoding = -1;
  hf_h245_H263VideoCapability_advancedPrediction = -1;
  hf_h245_H263VideoCapability_pbFrames = -1;
  hf_h245_H263VideoCapability_temporalSpatialTradeOffCapability = -1;
  hf_h245_H263VideoCapability_hrd_B = -1;
  hf_h245_H263VideoCapability_bppMaxKb = -1;
  hf_h245_H263VideoCapability_slowSqcifMPI = -1;
  hf_h245_H263VideoCapability_slowQcifMPI = -1;
  hf_h245_H263VideoCapability_slowCifMPI = -1;
  hf_h245_H263VideoCapability_slowCif4MPI = -1;
  hf_h245_H263VideoCapability_slowCif16MPI = -1;
  hf_h245_H263VideoCapability_errorCompensation = -1;
  ett_h245_H263VideoCapability_enhancementLayerInfo = -1;
  ett_h245_H263VideoCapability_h263Options = -1;
  hf_h245_EnhancementOptions_sqcifMPI = -1;
  hf_h245_EnhancementOptions_qcifMPI = -1;
  hf_h245_EnhancementOptions_cifMPI = -1;
  hf_h245_EnhancementOptions_cif4MPI = -1;
  hf_h245_EnhancementOptions_cif16MPI = -1;
  hf_h245_EnhancementOptions_maxBitRate = -1;
  hf_h245_EnhancementOptions_unrestrictedVector = -1;
  hf_h245_EnhancementOptions_arithmeticCoding = -1;
  hf_h245_EnhancementOptions_temporalSpatialTradeOffCapability = -1;
  hf_h245_EnhancementOptions_slowSqcifMPI = -1;
  hf_h245_EnhancementOptions_slowQcifMPI = -1;
  hf_h245_EnhancementOptions_slowCifMPI = -1;
  hf_h245_EnhancementOptions_slowCif4MPI = -1;
  hf_h245_EnhancementOptions_slowCif16MPI = -1;
  hf_h245_EnhancementOptions_errorCompensation = -1;
  ett_h245_EnhancementOptions_h263Options = -1;
  ett_h245_ModeElement_type = -1;
  ett_h245_ModeElement_h223ModeParameters = -1;
  ett_h245_ModeElement_v76ModeParameters = -1;
  ett_h245_ModeElement_h2250ModeParameters = -1;
  ett_h245_BEnhancementParameters_enhancementOptions = -1;
  hf_h245_BEnhancementParameters_numberOfBPictures = -1;
};



// End of h245_container3.cpp
