/* 
 * h245_container.h
 *
 * The main header for saving the H.245 ID's for Ethereal protocol items
 *
 * H.323 for Ethereal
 *
 * Copyright (c) 2002 Koninklijke Philips NV
 *
 * The contents of this file are subject to the Mozilla Public License
 * Version 1.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS"
 * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
 * the License for the specific language governing rights and limitations
 * under the License.
 *
 * The Original Code is H.323 for Ethereal.
 *
 * The Initial Developer of the Original Code is Koninklijke Philips NV.
 *
 * All Rights Reserved.
 *
 * Contributor(s): ______________________________________.
 *
 *
 */

//
// h245_container.h
//
// Code automatically generated by asnparse.
//

#ifndef __H245_CONTAINER_H
#define __H245_CONTAINER_H

#include "mini_ptlib/include/mini_ptlib.h"
#include "h245_container0.h"
#include "h245_container1.h"
#include "h245_container2.h"
#include "h245_container3.h"

class H245_Integer_Container : public PObject
{
    PCLASSINFO(H245_Integer_Container, PObject);
  public:
    H245_Integer_Container ();
    H245_0_Integer_Container h245_0;
    H245_1_Integer_Container h245_1;
    H245_2_Integer_Container h245_2;
    H245_3_Integer_Container h245_3;
};

#endif // end of header file

// End of h245_container.h
