/* 
 * h450_container1.cxx
 *
 * Sources for saving the ID's for Ethereal protocol items
 *
 * H.323 for Ethereal
 *
 * Copyright (c) 2002 Koninklijke Philips NV
 *
 * The contents of this file are subject to the Mozilla Public License
 * Version 1.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS"
 * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
 * the License for the specific language governing rights and limitations
 * under the License.
 *
 * The Original Code is H.323 for Ethereal.
 *
 * The Initial Developer of the Original Code is Koninklijke Philips NV.
 *
 * All Rights Reserved.
 *
 * Contributor(s): ______________________________________.
 *
 *
 */

//
// h450_container1.cxx
//
// Code automatically generated by asnparse.
//

#include "h450_container1.h"

H450_1_Integer_Container::H450_1_Integer_Container()
{
  ett_h450_ROS_choice = -1;
  hf_h450_Code_local = -1;
  hf_h450_Code_global = -1;
  hf_h450_EntityType_endpoint = -1;
  hf_h450_EntityType_anyEntity = -1;
  hf_h450_InterpretationApdu_discardAnyUnrecognizedInvokePdu = -1;
  hf_h450_InterpretationApdu_clearCallIfAnyInvokePduNotRecognized = -1;
  hf_h450_InterpretationApdu_rejectAnyUnrecognizedInvokePdu = -1;
  ett_h450_ServiceApdus_choice = -1;
  hf_h450_PresentedAddressScreened_presentationRestricted = -1;
  hf_h450_PresentedAddressScreened_numberNotAvailableDueToInterworking = -1;
  ett_h450_PresentedAddressScreened_choice = -1;
  hf_h450_PresentedAddressUnscreened_presentationRestricted = -1;
  hf_h450_PresentedAddressUnscreened_numberNotAvailableDueToInterworking = -1;
  ett_h450_PresentedAddressUnscreened_choice = -1;
  hf_h450_PresentedNumberScreened_presentationRestricted = -1;
  hf_h450_PresentedNumberScreened_numberNotAvailableDueToInterworking = -1;
  ett_h450_PresentedNumberScreened_choice = -1;
  hf_h450_PresentedNumberUnscreened_presentationRestricted = -1;
  hf_h450_PresentedNumberUnscreened_numberNotAvailableDueToInterworking = -1;
  ett_h450_PresentedNumberUnscreened_choice = -1;
  hf_h450_PartySubaddress_nsapSubaddress = -1;
  ett_h450_PartySubaddress_choice = -1;
  hf_h450_ScreeningIndicator_enum = -1;
  ett_h450_ScreeningIndicator = -1;
  hf_h450_GeneralErrorList_enum = -1;
  ett_h450_GeneralErrorList = -1;
  ett_h450_Extension_extensionId = -1;
  hf_h450_Extension_extensionArgument = -1;
  hf_h450_OperationName_enum = -1;
  ett_h450_OperationName = -1;
  ett_h450_MixedExtension_choice = -1;
  ett_h450_CcArg_choice = -1;
  hf_h450_CallCompletionErrors_enum = -1;
  ett_h450_CallCompletionErrors = -1;
  hf_h450_Name_nameNotAvailable = -1;
  ett_h450_Name_choice = -1;
  hf_h450_NamePresentationAllowed_simpleName = -1;
  hf_h450_NamePresentationAllowed_extendedName = -1;
  hf_h450_NamePresentationRestricted_simpleName = -1;
  hf_h450_NamePresentationRestricted_extendedName = -1;
  hf_h450_NamePresentationRestricted_restrictedNull = -1;
  ett_h450_DummyRes = -1;
  ett_h450_MWIInterrogateRes = -1;
  hf_h450_MsgCentreId_integer = -1;
  hf_h450_MsgCentreId_numericString = -1;
  ett_h450_MsgCentreId_choice = -1;
  hf_h450_MessageWaitingIndicationErrors_enum = -1;
  ett_h450_MessageWaitingIndicationErrors = -1;
  hf_h450_BasicService_enum = -1;
  ett_h450_BasicService = -1;
  hf_h450_ParkCondition_enum = -1;
  ett_h450_ParkCondition = -1;
  hf_h450_CallType_enum = -1;
  ett_h450_CallType = -1;
  hf_h450_CallPickupErrors_enum = -1;
  ett_h450_CallPickupErrors = -1;
  hf_h450_DiversionReason_enum = -1;
  ett_h450_DiversionReason = -1;
  ett_h450_IntResultList = -1;
  hf_h450_Procedure_enum = -1;
  ett_h450_Procedure = -1;
  hf_h450_SubscriptionOption_enum = -1;
  ett_h450_SubscriptionOption = -1;
  hf_h450_CallDiversionErrors_enum = -1;
  ett_h450_CallDiversionErrors = -1;
  ett_h450_DummyArg_choice = -1;
  hf_h450_EndDesignation_enum = -1;
  ett_h450_EndDesignation = -1;
  hf_h450_CallStatus_enum = -1;
  ett_h450_CallStatus = -1;
  ett_h450_ExtensionSeq = -1;
  hf_h450_CallTransferOperation_enum = -1;
  ett_h450_CallTransferOperation = -1;
  hf_h450_CallTransferErrors_enum = -1;
  ett_h450_CallTransferErrors = -1;
  hf_h450_CIStatusInformation_callIntrusionImpending = -1;
  hf_h450_CIStatusInformation_callIntruded = -1;
  hf_h450_CIStatusInformation_callIsolated = -1;
  hf_h450_CIStatusInformation_callForceReleased = -1;
  hf_h450_CIStatusInformation_callIntrusionComplete = -1;
  hf_h450_CIStatusInformation_callIntrusionEnd = -1;
  hf_h450_CallIntrusionErrors_enum = -1;
  ett_h450_CallIntrusionErrors = -1;
  ett_h450_ReturnResult_result_opcode = -1;
  hf_h450_ReturnResult_result_result = -1;
  hf_h450_Reject_problem_general = -1;
  hf_h450_Reject_problem_invoke = -1;
  hf_h450_Reject_problem_returnResult = -1;
  hf_h450_Reject_problem_returnError = -1;
  ett_h450_ArrayOf_ROS = -1;
  ett_h450_ArrayOf_AliasAddress = -1;
  ett_h450_ArrayOf_MixedExtension = -1;
  ett_h450_IntResult_extension_choice = -1;
  ett_h450_CTInitiateArg_argumentExtension_choice = -1;
  ett_h450_CTSetupArg_argumentExtension_choice = -1;
  ett_h450_CTIdentifyRes_resultExtension_choice = -1;
  ett_h450_CTUpdateArg_argumentExtension_choice = -1;
  ett_h450_SubaddressTransferArg_argumentExtension_choice = -1;
  ett_h450_CTCompleteArg_argumentExtension_choice = -1;
  ett_h450_CTActiveArg_argumentExtension_choice = -1;
  hf_h450_Invoke_invokeId = -1;
  hf_h450_Invoke_linkedId = -1;
  ett_h450_Invoke_opcode = -1;
  hf_h450_Invoke_argument = -1;
  ett_h450_Invoke_argument = -1;
  hf_h450_ReturnResult_invokeId = -1;
  ett_h450_ReturnResult_result = -1;
  hf_h450_ReturnError_invokeId = -1;
  ett_h450_ReturnError_errorCode = -1;
  hf_h450_ReturnError_parameter = -1;
  hf_h450_Reject_invokeId = -1;
  ett_h450_Reject_problem = -1;
  ett_h450_NetworkFacilityExtension_sourceEntity = -1;
  ett_h450_NetworkFacilityExtension_sourceEntityAddress = -1;
  ett_h450_NetworkFacilityExtension_destinationEntity = -1;
  ett_h450_NetworkFacilityExtension_destinationEntityAddress = -1;
  ett_h450_AddressScreened_partyNumber = -1;
  ett_h450_AddressScreened_screeningIndicator = -1;
  ett_h450_AddressScreened_partySubaddress = -1;
  ett_h450_NumberScreened_partyNumber = -1;
  ett_h450_NumberScreened_screeningIndicator = -1;
  ett_h450_Address_partyNumber = -1;
  ett_h450_Address_partySubaddress = -1;
  ett_h450_EndpointAddress_destinationAddress = -1;
  ett_h450_EndpointAddress_remoteExtensionAddress = -1;
  hf_h450_UserSpecifiedSubaddress_subaddressInformation = -1;
  hf_h450_UserSpecifiedSubaddress_oddCountIndicator = -1;
  ett_h450_HoldNotificArg_extensionArg = -1;
  ett_h450_RetrieveNotificArg_extensionArg = -1;
  ett_h450_RemoteHoldArg_extensionArg = -1;
  ett_h450_RemoteHoldRes_extensionRes = -1;
  ett_h450_RemoteRetrieveArg_extensionArg = -1;
  ett_h450_RemoteRetrieveRes_extensionRes = -1;
  ett_h450_CcRequestArg_numberA = -1;
  ett_h450_CcRequestArg_numberB = -1;
  ett_h450_CcRequestArg_ccIdentifier = -1;
  ett_h450_CcRequestArg_service = -1;
  hf_h450_CcRequestArg_can_retain_service = -1;
  hf_h450_CcRequestArg_retain_sig_connection = -1;
  ett_h450_CcRequestArg_extension = -1;
  hf_h450_CcRequestRes_retain_service = -1;
  ett_h450_CcRequestRes_extension = -1;
  ett_h450_CcShortArg_ccIdentifier = -1;
  ett_h450_CcShortArg_extension = -1;
  ett_h450_CcLongArg_numberA = -1;
  ett_h450_CcLongArg_numberB = -1;
  ett_h450_CcLongArg_ccIdentifier = -1;
  ett_h450_CcLongArg_service = -1;
  ett_h450_CcLongArg_extension = -1;
  ett_h450_MWIActivateArg_servedUserNr = -1;
  ett_h450_MWIActivateArg_basicService = -1;
  ett_h450_MWIActivateArg_msgCentreId = -1;
  hf_h450_MWIActivateArg_nbOfMessages = -1;
  ett_h450_MWIActivateArg_originatingNr = -1;
  hf_h450_MWIActivateArg_timestamp = -1;
  hf_h450_MWIActivateArg_priority = -1;
  ett_h450_MWIActivateArg_extensionArg = -1;
  ett_h450_MWIDeactivateArg_servedUserNr = -1;
  ett_h450_MWIDeactivateArg_basicService = -1;
  ett_h450_MWIDeactivateArg_msgCentreId = -1;
  hf_h450_MWIDeactivateArg_callbackReq = -1;
  ett_h450_MWIDeactivateArg_extensionArg = -1;
  ett_h450_MWIInterrogateArg_servedUserNr = -1;
  ett_h450_MWIInterrogateArg_basicService = -1;
  ett_h450_MWIInterrogateArg_msgCentreId = -1;
  hf_h450_MWIInterrogateArg_callbackReq = -1;
  ett_h450_MWIInterrogateArg_extensionArg = -1;
  ett_h450_MWIInterrogateResElt_basicService = -1;
  ett_h450_MWIInterrogateResElt_msgCentreId = -1;
  hf_h450_MWIInterrogateResElt_nbOfMessages = -1;
  ett_h450_MWIInterrogateResElt_originatingNr = -1;
  hf_h450_MWIInterrogateResElt_timestamp = -1;
  hf_h450_MWIInterrogateResElt_priority = -1;
  ett_h450_MWIInterrogateResElt_extensionArg = -1;
  ett_h450_CoReqOptArg_extension = -1;
  ett_h450_RUAlertOptArg_extension = -1;
  ett_h450_CfbOvrOptArg_extension = -1;
  ett_h450_CpRequestArg_parkingNumber = -1;
  ett_h450_CpRequestArg_parkedNumber = -1;
  ett_h450_CpRequestArg_parkedToNumber = -1;
  hf_h450_CpRequestArg_parkedToPosition = -1;
  ett_h450_CpRequestArg_extensionArg = -1;
  ett_h450_CpRequestRes_parkedToNumber = -1;
  hf_h450_CpRequestRes_parkedToPosition = -1;
  ett_h450_CpRequestRes_parkCondition = -1;
  ett_h450_CpRequestRes_extensionRes = -1;
  ett_h450_CpSetupArg_parkingNumber = -1;
  ett_h450_CpSetupArg_parkedNumber = -1;
  ett_h450_CpSetupArg_parkedToNumber = -1;
  hf_h450_CpSetupArg_parkedToPosition = -1;
  ett_h450_CpSetupArg_extensionArg = -1;
  ett_h450_CpSetupRes_parkedToNumber = -1;
  hf_h450_CpSetupRes_parkedToPosition = -1;
  ett_h450_CpSetupRes_parkCondition = -1;
  ett_h450_CpSetupRes_extensionRes = -1;
  ett_h450_GroupIndicationOnArg_callPickupId = -1;
  ett_h450_GroupIndicationOnArg_groupMemberUserNr = -1;
  ett_h450_GroupIndicationOnArg_retrieveCallType = -1;
  ett_h450_GroupIndicationOnArg_partyToRetrieve = -1;
  ett_h450_GroupIndicationOnArg_retrieveAddress = -1;
  hf_h450_GroupIndicationOnArg_parkPosition = -1;
  ett_h450_GroupIndicationOnArg_extensionArg = -1;
  ett_h450_GroupIndicationOnRes_extensionRes = -1;
  ett_h450_GroupIndicationOffArg_callPickupId = -1;
  ett_h450_GroupIndicationOffArg_groupMemberUserNr = -1;
  ett_h450_GroupIndicationOffArg_extensionArg = -1;
  ett_h450_GroupIndicationOffRes_extensionRes = -1;
  ett_h450_PickrequArg_picking_upNumber = -1;
  ett_h450_PickrequArg_callPickupId = -1;
  ett_h450_PickrequArg_partyToRetrieve = -1;
  ett_h450_PickrequArg_retrieveAddress = -1;
  hf_h450_PickrequArg_parkPosition = -1;
  ett_h450_PickrequArg_extensionArg = -1;
  ett_h450_PickrequRes_callPickupId = -1;
  ett_h450_PickrequRes_extensionRes = -1;
  ett_h450_PickupArg_callPickupId = -1;
  ett_h450_PickupArg_picking_upNumber = -1;
  ett_h450_PickupArg_extensionArg = -1;
  ett_h450_PickupRes_extensionRes = -1;
  ett_h450_PickExeArg_callPickupId = -1;
  ett_h450_PickExeArg_picking_upNumber = -1;
  ett_h450_PickExeArg_partyToRetrieve = -1;
  ett_h450_PickExeArg_extensionArg = -1;
  ett_h450_PickExeRes_extensionRes = -1;
  ett_h450_CpNotifyArg_parkingNumber = -1;
  ett_h450_CpNotifyArg_extensionArg = -1;
  ett_h450_CpickupNotifyArg_picking_upNumber = -1;
  ett_h450_CpickupNotifyArg_extensionArg = -1;
  ett_h450_IntResult_servedUserNr = -1;
  ett_h450_IntResult_basicService = -1;
  ett_h450_IntResult_procedure = -1;
  ett_h450_IntResult_divertedToAddress = -1;
  hf_h450_IntResult_remoteEnabled = -1;
  ett_h450_IntResult_extension = -1;
  hf_h450_CTInitiateArg_callIdentity = -1;
  ett_h450_CTInitiateArg_reroutingNumber = -1;
  ett_h450_CTInitiateArg_argumentExtension = -1;
  hf_h450_CTSetupArg_callIdentity = -1;
  ett_h450_CTSetupArg_transferringNumber = -1;
  ett_h450_CTSetupArg_argumentExtension = -1;
  hf_h450_CTIdentifyRes_callIdentity = -1;
  ett_h450_CTIdentifyRes_reroutingNumber = -1;
  ett_h450_CTIdentifyRes_resultExtension = -1;
  ett_h450_CTUpdateArg_redirectionNumber = -1;
  hf_h450_CTUpdateArg_redirectionInfo = -1;
  hf_h450_CTUpdateArg_basicCallInfoElements = -1;
  ett_h450_CTUpdateArg_argumentExtension = -1;
  ett_h450_SubaddressTransferArg_redirectionSubaddress = -1;
  ett_h450_SubaddressTransferArg_argumentExtension = -1;
  ett_h450_CTCompleteArg_endDesignation = -1;
  ett_h450_CTCompleteArg_redirectionNumber = -1;
  hf_h450_CTCompleteArg_basicCallInfoElements = -1;
  hf_h450_CTCompleteArg_redirectionInfo = -1;
  ett_h450_CTCompleteArg_callStatus = -1;
  ett_h450_CTCompleteArg_argumentExtension = -1;
  ett_h450_CTActiveArg_connectedAddress = -1;
  hf_h450_CTActiveArg_basicCallInfoElements = -1;
  hf_h450_CTActiveArg_connectedInfo = -1;
  ett_h450_CTActiveArg_argumentExtension = -1;
  hf_h450_CIRequestArg_ciCapabilityLevel = -1;
  ett_h450_CIRequestArg_argumentExtension = -1;
  ett_h450_CIRequestRes_ciStatusInformation = -1;
  ett_h450_CIRequestRes_resultExtension = -1;
  ett_h450_CIGetCIPLOptArg_argumentExtension = -1;
  hf_h450_CIGetCIPLRes_ciProtectionLevel = -1;
  hf_h450_CIGetCIPLRes_silentMonitoringPermitted = -1;
  ett_h450_CIGetCIPLRes_resultExtension = -1;
  ett_h450_CIIsOptArg_argumentExtension = -1;
  ett_h450_CIIsOptRes_resultExtension = -1;
  hf_h450_CIFrcRelArg_ciCapabilityLevel = -1;
  ett_h450_CIFrcRelArg_argumentExtension = -1;
  ett_h450_CIFrcRelOptRes_resultExtension = -1;
  ett_h450_CIWobOptArg_argumentExtension = -1;
  ett_h450_CIWobOptRes_resultExtension = -1;
  hf_h450_CISilentArg_ciCapabilityLevel = -1;
  ett_h450_CISilentArg_specificCall = -1;
  ett_h450_CISilentArg_argumentExtension = -1;
  ett_h450_CISilentOptRes_resultExtension = -1;
  ett_h450_CINotificationArg_ciStatusInformation = -1;
  ett_h450_CINotificationArg_argumentExtension = -1;
  hf_h450_CallWaitingArg_nbOfAddWaitingCalls = -1;
  ett_h450_CallWaitingArg_extensionArg = -1;
  ett_h450_SupplementaryService_networkFacilityExtension = -1;
  ett_h450_SupplementaryService_interpretationApdu = -1;
  ett_h450_SupplementaryService_serviceApdu = -1;
};



// End of h450_container1.cxx
