/* 
 * h450_container.h
 *
 * Main header for saving the H.450 ID's for Ethereal protocol items
 *
 * H.323 for Ethereal
 *
 * Copyright (c) 2002 Koninklijke Philips NV
 *
 * The contents of this file are subject to the Mozilla Public License
 * Version 1.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS"
 * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
 * the License for the specific language governing rights and limitations
 * under the License.
 *
 * The Original Code is H.323 for Ethereal.
 *
 * The Initial Developer of the Original Code is Koninklijke Philips NV.
 *
 * All Rights Reserved.
 *
 * Contributor(s): ______________________________________.
 *
 *
 */

//
// h450_container.h
//
// Code automatically generated by asnparse.
//

#ifndef __H450_CONTAINER_H
#define __H450_CONTAINER_H

#include "mini_ptlib/include/mini_ptlib.h"
#include "h450_container0.h"
#include "h450_container1.h"

class H450_Integer_Container : public PObject
{
    PCLASSINFO(H450_Integer_Container, PObject);
  public:
    H450_Integer_Container ();
    H450_0_Integer_Container h450_0;
    H450_1_Integer_Container h450_1;
};

#endif // end of header file

// End of h450_container.h
